# Generated by Django 5.1.4 on 2024-12-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkboxstate',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
